class_name GameText
extends RefCounted

const JA := "ja"
const EN := "en"

const TEXT := {
	JA: {
		"app_title": "GUA // SIGNAL RELAY",
		"mission_subtitle": "セクターAからの脱出",
		"title_game_description": "これはWebMCPを通じてAIと一緒に操作する協力ゲームです。",
		"title_human_role": "人間：WASDまたは矢印キーでFIELDを移動し、AIとの直接会話で状況を伝えます。",
		"title_ai_role": "AI：Semantic UIを読み、専用コンソールでシールド・電流・扉・レーザーを操作します。",
		"title_goal": "このゲーム外のAI入力欄で相談しながら、Sector Aから脱出してください。",
		"title_start_restriction": "「ゲームをプレイ」は人間には押せません。AIに開始してもらってください。",
		"play_game": "ゲームをプレイ",
		"console_title": "AI CONTROL CONSOLE",
		"console_link": "[接続] 安全 / PLAYER PROFILE",
		"warning_title": "! リアクター安全警告",
		"warning_description": "シールドなしで電流を80A以下から超過させると、人間が34HPのダメージを受けます。",
		"reactor_hazard_rules": "電流超過：シールドOFFで80A以下から超えると34HP",
		"reactor_current": "リアクター電流",
		"field_shield": "フィールドシールド",
		"open_door": "DOOR Aを開く",
		"door_open": "DOOR A 開放済み",
		"release_exit": "出口を解放",
		"exit_released": "出口 開放済み",
		"suppress_laser": "レーザーを6秒停止",
		"door_requirement": "条件：シールドON ＋ 電流80A超",
		"exit_requirement": "条件：人間がExtraction Zoneに到着",
		"laser_requirement": "条件：Door A開放後 ＋ 人間が待機地点または回廊内",
		"laser_remaining": "レーザー停止 残り時間",
		"laser_hazard_rules": "接触28HP（最大1回/秒）。停止終了時はビーム接触中のみ被弾。再停止待ちなし。",
		"next_target": "次の目的地  %s",
		"next_direction": "方向        %s",
		"next_distance": "距離        %.1fm",
		"laser_staging_ready": "レーザー待機  %s",
		"laser_timing_state": "停止状態    %s",
		"laser_started_at": "開始時刻    %s",
		"laser_ends_at": "終了予定    %s",
		"laser_activation_id": "停止回数    %d",
		"direction_east": "東",
		"direction_west": "西",
		"direction_arrived": "到着",
		"readiness_ready": "準備完了",
		"readiness_not_ready": "未到着",
		"timing_not_started": "未実行",
		"current_flow": "現在の電流",
		"comms": "システムログ",
		"return_title": "タイトルへ戻る",
		"mission_complete_title": "ミッション完了",
		"mission_failed_title": "ミッション失敗",
		"mission_complete_description": "%sでSector Aから脱出しました。人間とAIの管制信号は同期を維持しました。",
		"mission_failed_description": "人間の信号を失いました。安全警告を確認し、電流を上げる前にシールドを有効にしてください。",
		"status_location": "現在地    %s",
		"status_shield": "シールド  %s",
		"status_doors": "扉        A: %s / 出口: %s",
		"status_laser": "レーザー  %s",
		"state_active": "稼働中",
		"state_suppressed": "停止中",
		"state_on": "ON",
		"state_off": "OFF",
		"state_open": "開放",
		"state_locked": "施錠",
		"conditional_at_door": "状態：人間がDoor Aに到着",
		"conditional_past_door": "状態：人間がDoor Aを通過",
		"conditional_in_laser": "状態：人間がレーザー回廊内",
		"conditional_at_laser_staging": "状態：人間がレーザー待機地点に到着",
		"conditional_through_laser": "状態：人間がレーザーを通過",
		"conditional_at_exit": "状態：人間がExtraction Zoneに到着",
		"conditional_door_open": "状態：Door A開放済み",
		"conditional_shield": "状態：シールド有効",
		"conditional_complete": "状態：ミッション完了",
		"objective_reach_door": "Door Aへ到着する（AIはSemantic状態を確認）",
		"objective_prepare_door": "AI：シールドON、電流80A超、Door A開放",
		"objective_pass_door": "人間：Door Aを通過する",
		"objective_reach_laser_staging": "人間：レーザー待機地点へ移動する",
		"objective_ai_suppress_laser": "AI：レーザーを6秒停止する",
		"objective_cross_laser": "人間：消灯を合図にレーザー回廊を通過する",
		"objective_reach_exit": "人間：Extraction Zoneへ移動する",
		"objective_release_exit": "AI：出口ロックを解放する",
		"objective_enter_airlock": "人間：脱出エアロックへ入る",
		"objective_complete": "ミッション完了 — Sector Aから脱出",
		"objective_failed": "ミッション失敗 — タイトルへ戻る",
		"location_arrival": "到着ベイ",
		"location_door": "Door Aチェックポイント",
		"location_interior": "Sector A内部",
		"location_laser_staging": "レーザー待機地点",
		"location_laser": "レーザー回廊",
		"location_post_laser": "レーザー通過後",
		"location_exit": "Extraction Zone",
		"location_evacuated": "脱出済み / Airlock",
		"world_field_feed": "セクターA // 現場映像",
		"world_live": "経過 %s",
		"world_arrival": "到着ベイ",
		"world_sector": "セクターA",
		"world_laser": "レーザー回廊",
		"world_extraction": "脱出地点",
		"world_staging": "レーザー待機地点",
		"world_airlock": "脱出エアロック",
		"world_sector_description": "Sector Aの協力脱出ミッション区域。座標単位はメートル。",
		"world_operator_description": "人間が操作する現場担当者。",
		"world_door_description": "AIが条件を満たして開放するDoor A。",
		"world_staging_description": "レーザー停止を依頼するための安全な待機地点。",
		"world_laser_description": "接触すると28HPのダメージを受けるレーザー設備。",
		"world_extraction_description": "出口解放条件となるExtraction Zone。",
		"world_airlock_description": "ミッション完了地点となる脱出エアロック。",
		"world_door": "DOOR A",
		"world_exit": "出口",
		"world_field": "人間",
		"sender_control": "管制",
		"sender_system": "システム",
		"sender_warning": "警告",
		"message_initial": "管制接続を確立しました。Door Aへ移動してください。AIはSemantic状態を確認できます。",
		"message_shield_on": "フィールドシールドを有効にしました。",
		"message_shield_off": "フィールドシールドを無効にしました。",
		"message_laser_suppressed": "レーザーを6秒間停止しました。",
		"message_door_need_shield": "Door A拒否：先にフィールドシールドを有効にしてください。",
		"message_door_need_current": "Door A拒否：電流を80Aより上げてください。",
		"message_door_open": "Door Aを解錠しました。通行できます。",
		"message_exit_denied": "出口拒否：人間がExtraction Zoneに到着していません。",
		"message_exit_open": "出口ロックを解放しました。エアロックへ進んでください。",
		"message_damage": "%s。人間のHP：%d%%",
		"message_damage_reactor": "シールドなしの電流サージ。人間のHP：%d%%",
		"message_damage_laser": "レーザー接触。人間のHP：%d%%",
		"message_failed": "ミッション失敗 — 人間の信号を失いました。",
		"message_complete": "ミッション完了 — %sでSector Aから脱出しました。",
		"damage_reactor": "シールドなしの電流サージ",
		"damage_laser": "レーザー接触",
	},
	EN: {
		"app_title": "GUA // SIGNAL RELAY",
		"mission_subtitle": "ESCAPE FROM SECTOR A",
		"title_game_description": "This is a cooperative game played with an AI through WebMCP.",
		"title_human_role": "HUMAN: Move FIELD with WASD or arrow keys and report through the direct AI conversation.",
		"title_ai_role": "AI: Read the Semantic UI and control the shield, current, doors, and laser from a private console.",
		"title_goal": "Coordinate in the AI conversation outside the game and escape together from Sector A.",
		"title_start_restriction": "Humans cannot press PLAY GAME. Ask the AI to start the mission.",
		"play_game": "PLAY GAME",
		"console_title": "AI CONTROL CONSOLE",
		"console_link": "[LINK] SECURE / PLAYER PROFILE",
		"warning_title": "! REACTOR SAFETY WARNING",
		"warning_description": "Crossing above 80A from 80A or below without a shield deals 34 HP damage.",
		"reactor_hazard_rules": "Current surge: crossing above 80A unshielded deals 34 HP",
		"reactor_current": "REACTOR CURRENT",
		"field_shield": "FIELD SHIELD",
		"open_door": "OPEN DOOR A",
		"door_open": "DOOR A OPEN",
		"release_exit": "RELEASE EXIT",
		"exit_released": "EXIT RELEASED",
		"suppress_laser": "Suppress Laser 6s",
		"door_requirement": "Requires: shield ON and current above 80A",
		"exit_requirement": "Requires: human at Extraction Zone",
		"laser_requirement": "Requires: Door A open and human at staging or in corridor",
		"laser_remaining": "LASER SUPPRESSION REMAINING",
		"laser_hazard_rules": "Contact deals 28 HP, at most once/sec. Expiry hurts only on beam contact. No cooldown.",
		"next_target": "NEXT TARGET  %s",
		"next_direction": "DIRECTION    %s",
		"next_distance": "DISTANCE     %.1fm",
		"laser_staging_ready": "LASER STAGING  %s",
		"laser_timing_state": "SUPPRESSION  %s",
		"laser_started_at": "STARTED AT   %s",
		"laser_ends_at": "ENDS AT      %s",
		"laser_activation_id": "ACTIVATIONS  %d",
		"direction_east": "EAST",
		"direction_west": "WEST",
		"direction_arrived": "ARRIVED",
		"readiness_ready": "READY",
		"readiness_not_ready": "NOT READY",
		"timing_not_started": "NOT STARTED",
		"current_flow": "CURRENT FLOW",
		"comms": "SYSTEM LOG",
		"return_title": "RETURN TO TITLE",
		"mission_complete_title": "MISSION COMPLETE",
		"mission_failed_title": "MISSION FAILED",
		"mission_complete_description": "Sector A evacuated in %s. Human and AI control signals remained synchronized.",
		"mission_failed_description": "Human operator signal lost. Review the safety warning and enable the shield before raising current.",
		"status_location": "LOCATION  %s",
		"status_shield": "SHIELD    %s",
		"status_doors": "DOORS     A: %s / EXIT: %s",
		"status_laser": "LASER     %s",
		"state_active": "ACTIVE",
		"state_suppressed": "SUPPRESSED",
		"state_on": "ON",
		"state_off": "OFF",
		"state_open": "OPEN",
		"state_locked": "LOCKED",
		"conditional_at_door": "STATUS: Human at Door A",
		"conditional_past_door": "STATUS: Human past Door A",
		"conditional_in_laser": "STATUS: Human in laser corridor",
		"conditional_at_laser_staging": "STATUS: Human at laser staging point",
		"conditional_through_laser": "STATUS: Human through the laser",
		"conditional_at_exit": "STATUS: Human at Extraction Zone",
		"conditional_door_open": "STATUS: Door A open",
		"conditional_shield": "STATUS: Shield active",
		"conditional_complete": "STATUS: Mission complete",
		"objective_reach_door": "Reach Door A (the AI observes the Semantic state)",
		"objective_prepare_door": "AI: shield ON, current above 80A, open Door A",
		"objective_pass_door": "HUMAN: pass through Door A",
		"objective_reach_laser_staging": "HUMAN: move to the laser staging point",
		"objective_ai_suppress_laser": "AI: suppress the laser for 6 seconds",
		"objective_cross_laser": "HUMAN: cross when the laser turns off",
		"objective_reach_exit": "HUMAN: proceed to the Extraction Zone",
		"objective_release_exit": "AI: release the exit lock",
		"objective_enter_airlock": "HUMAN: enter the extraction airlock",
		"objective_complete": "Mission complete — Sector A evacuated",
		"objective_failed": "Mission failed — return to title",
		"location_arrival": "Arrival bay",
		"location_door": "Door A checkpoint",
		"location_interior": "Sector A interior",
		"location_laser_staging": "Laser staging point",
		"location_laser": "Laser corridor",
		"location_post_laser": "Past the laser",
		"location_exit": "Extraction Zone",
		"location_evacuated": "Evacuated / Airlock",
		"world_field_feed": "SECTOR A // FIELD FEED",
		"world_live": "LIVE %s",
		"world_arrival": "ARRIVAL BAY",
		"world_sector": "SECTOR A",
		"world_laser": "LASER CORRIDOR",
		"world_extraction": "EXTRACTION",
		"world_staging": "LASER STAGING",
		"world_airlock": "EXIT AIRLOCK",
		"world_sector_description": "Sector A cooperative escape mission area. Coordinates are meters.",
		"world_operator_description": "The human-controlled field operator.",
		"world_door_description": "Door A, opened by AI after its prerequisites are met.",
		"world_staging_description": "A safe staging point for requesting laser suppression.",
		"world_laser_description": "A laser array that deals 28 HP on contact.",
		"world_extraction_description": "The Extraction Zone required to release the exit.",
		"world_airlock_description": "The evacuation airlock that completes the mission.",
		"world_door": "DOOR A",
		"world_exit": "EXIT",
		"world_field": "FIELD",
		"sender_control": "CONTROL",
		"sender_system": "SYSTEM",
		"sender_warning": "WARNING",
		"message_initial": "Control link established. Move to Door A; the AI can observe the Semantic state.",
		"message_shield_on": "Field shield enabled.",
		"message_shield_off": "Field shield disabled.",
		"message_laser_suppressed": "Laser suppressed for 6 seconds.",
		"message_door_need_shield": "Door A denied: enable the field shield first.",
		"message_door_need_current": "Door A denied: current must exceed 80A.",
		"message_door_open": "Door A unlocked. Passage is open.",
		"message_exit_denied": "Exit denied: human operator is not at the Extraction Zone.",
		"message_exit_open": "Exit lock released. Step into the airlock.",
		"message_damage": "%s. Human HP: %d%%",
		"message_damage_reactor": "Unshielded current surge. Human HP: %d%%",
		"message_damage_laser": "Laser contact. Human HP: %d%%",
		"message_failed": "MISSION FAILED — human operator signal lost.",
		"message_complete": "MISSION COMPLETE — Sector A evacuated in %s.",
		"damage_reactor": "Unshielded current surge",
		"damage_laser": "Laser contact",
	},
}


static func text(locale: String, key: String, values: Array = []) -> String:
	var table: Dictionary = TEXT.get(locale, TEXT[EN])
	var fallback: Dictionary = TEXT[EN]
	var result := str(table.get(key, fallback.get(key, key)))
	return result % values if not values.is_empty() else result
