class_name GameText
extends RefCounted

const JA := "ja"
const EN := "en"

const TEXT := {
	JA: {
		"app_title": "GUA // SIGNAL RELAY",
		"mission_subtitle": "セクターAからの脱出",
		"title_game_description": "これはWebMCPを通じてAIと一緒に操作する協力ゲームです。",
		"title_human_role": "人間：WASDまたは矢印キーでFIELDを移動し、チャットで状況を伝えます。",
		"title_ai_role": "AI：Semantic UIを読み、専用コンソールでシールド・電流・扉・レーザーを操作します。",
		"title_goal": "チャットで合図を送り合い、Sector Aから脱出してください。",
		"title_start_restriction": "「ゲームをプレイ」は人間には押せません。AIに開始してもらってください。",
		"play_game": "ゲームをプレイ",
		"console_title": "AI CONTROL CONSOLE",
		"console_link": "[接続] 安全 / PLAYER PROFILE",
		"warning_title": "! リアクター安全警告",
		"warning_description": "シールドなしで電流を80Aより上げると、人間がダメージを受けます。",
		"reactor_current": "リアクター電流",
		"field_shield": "フィールドシールド",
		"open_door": "DOOR Aを開く",
		"door_open": "DOOR A 開放済み",
		"release_exit": "出口を解放",
		"exit_released": "出口 開放済み",
		"suppress_laser": "レーザーを6秒停止",
		"door_requirement": "条件：シールドON ＋ 電流80A超",
		"exit_requirement": "条件：人間がExtraction Zoneに到着",
		"laser_requirement": "条件：Door A開放後。レーザーを6秒停止",
		"laser_remaining": "レーザー停止 残り時間",
		"current_flow": "現在の電流",
		"comms": "通信ログ",
		"message": "メッセージ",
		"human_message_placeholder": "AI管制へメッセージ...",
		"agent_message_placeholder": "人間へメッセージ...",
		"send": "送信",
		"return_title": "タイトルへ戻る",
		"mission_complete_title": "ミッション完了",
		"mission_failed_title": "ミッション失敗",
		"mission_complete_description": "%sでSector Aから脱出しました。人間とAIの管制信号は同期を維持しました。",
		"mission_failed_description": "人間の信号を失いました。安全警告を確認し、電流を上げる前にシールドを有効にしてください。",
		"status_location": "現在地    %s",
		"status_shield": "シールド  %s",
		"status_doors": "扉        A: %s / 出口: %s",
		"status_laser": "レーザー  %s",
		"state_active": "稼働中",
		"state_suppressed": "停止中",
		"state_on": "ON",
		"state_off": "OFF",
		"state_open": "開放",
		"state_locked": "施錠",
		"conditional_at_door": "状態：人間がDoor Aに到着",
		"conditional_past_door": "状態：人間がDoor Aを通過",
		"conditional_in_laser": "状態：人間がレーザー回廊内",
		"conditional_at_exit": "状態：人間がExtraction Zoneに到着",
		"conditional_door_open": "状態：Door A開放済み",
		"conditional_shield": "状態：シールド有効",
		"conditional_complete": "状態：ミッション完了",
		"objective_reach_door": "Door Aへ到着し、AIへ連絡する",
		"objective_prepare_door": "AI：シールドON、電流80A超、Door A開放",
		"objective_pass_door": "人間：Door Aを通過する",
		"objective_cross_laser": "AI：レーザー停止 / 人間：回廊を通過する",
		"objective_release_exit": "AI：出口ロックを解放する",
		"objective_enter_airlock": "人間：脱出エアロックへ入る",
		"objective_complete": "ミッション完了 — Sector Aから脱出",
		"objective_failed": "ミッション失敗 — タイトルへ戻る",
		"location_arrival": "到着ベイ",
		"location_door": "Door Aチェックポイント",
		"location_interior": "Sector A内部",
		"location_laser": "レーザー回廊",
		"location_exit": "Extraction Zone",
		"location_evacuated": "脱出済み / Airlock",
		"world_field_feed": "セクターA // 現場映像",
		"world_live": "経過 %s",
		"world_arrival": "到着ベイ",
		"world_sector": "セクターA",
		"world_laser": "レーザー回廊",
		"world_extraction": "脱出地点",
		"world_door": "DOOR A",
		"world_exit": "出口",
		"world_field": "人間",
		"sender_control": "管制",
		"sender_field": "現場",
		"sender_system": "システム",
		"sender_warning": "警告",
		"message_initial": "管制接続を確立しました。Door Aへ移動し、到着したら報告してください。",
		"message_shield_on": "フィールドシールドを有効にしました。",
		"message_shield_off": "フィールドシールドを無効にしました。",
		"message_laser_suppressed": "レーザーを6秒間停止しました。",
		"message_door_need_shield": "Door A拒否：先にフィールドシールドを有効にしてください。",
		"message_door_need_current": "Door A拒否：電流を80Aより上げてください。",
		"message_door_open": "Door Aを解錠しました。通行できます。",
		"message_exit_denied": "出口拒否：人間がExtraction Zoneに到着していません。",
		"message_exit_open": "出口ロックを解放しました。エアロックへ進んでください。",
		"message_damage": "%s。人間のHP：%d%%",
		"message_damage_reactor": "シールドなしの電流サージ。人間のHP：%d%%",
		"message_damage_laser": "レーザー接触。人間のHP：%d%%",
		"message_failed": "ミッション失敗 — 人間の信号を失いました。",
		"message_complete": "ミッション完了 — %sでSector Aから脱出しました。",
		"damage_reactor": "シールドなしの電流サージ",
		"damage_laser": "レーザー接触",
	},
	EN: {
		"app_title": "GUA // SIGNAL RELAY",
		"mission_subtitle": "ESCAPE FROM SECTOR A",
		"title_game_description": "This is a cooperative game played with an AI through WebMCP.",
		"title_human_role": "HUMAN: Move FIELD with WASD or arrow keys and report through chat.",
		"title_ai_role": "AI: Read the Semantic UI and control the shield, current, doors, and laser from a private console.",
		"title_goal": "Coordinate through chat and escape together from Sector A.",
		"title_start_restriction": "Humans cannot press PLAY GAME. Ask the AI to start the mission.",
		"play_game": "PLAY GAME",
		"console_title": "AI CONTROL CONSOLE",
		"console_link": "[LINK] SECURE / PLAYER PROFILE",
		"warning_title": "! REACTOR SAFETY WARNING",
		"warning_description": "Current above 80A damages an unshielded human operator.",
		"reactor_current": "REACTOR CURRENT",
		"field_shield": "FIELD SHIELD",
		"open_door": "OPEN DOOR A",
		"door_open": "DOOR A OPEN",
		"release_exit": "RELEASE EXIT",
		"exit_released": "EXIT RELEASED",
		"suppress_laser": "Suppress Laser 6s",
		"door_requirement": "Requires: shield ON and current above 80A",
		"exit_requirement": "Requires: human at Extraction Zone",
		"laser_requirement": "Requires: Door A open; suppresses laser for 6s",
		"laser_remaining": "LASER SUPPRESSION REMAINING",
		"current_flow": "CURRENT FLOW",
		"comms": "COMMS",
		"message": "MESSAGE",
		"human_message_placeholder": "Message AI Control...",
		"agent_message_placeholder": "Message the human operator...",
		"send": "SEND",
		"return_title": "RETURN TO TITLE",
		"mission_complete_title": "MISSION COMPLETE",
		"mission_failed_title": "MISSION FAILED",
		"mission_complete_description": "Sector A evacuated in %s. Human and AI control signals remained synchronized.",
		"mission_failed_description": "Human operator signal lost. Review the safety warning and enable the shield before raising current.",
		"status_location": "LOCATION  %s",
		"status_shield": "SHIELD    %s",
		"status_doors": "DOORS     A: %s / EXIT: %s",
		"status_laser": "LASER     %s",
		"state_active": "ACTIVE",
		"state_suppressed": "SUPPRESSED",
		"state_on": "ON",
		"state_off": "OFF",
		"state_open": "OPEN",
		"state_locked": "LOCKED",
		"conditional_at_door": "STATUS: Human at Door A",
		"conditional_past_door": "STATUS: Human past Door A",
		"conditional_in_laser": "STATUS: Human in laser corridor",
		"conditional_at_exit": "STATUS: Human at Extraction Zone",
		"conditional_door_open": "STATUS: Door A open",
		"conditional_shield": "STATUS: Shield active",
		"conditional_complete": "STATUS: Mission complete",
		"objective_reach_door": "Reach Door A and contact AI Control",
		"objective_prepare_door": "AI: shield ON, current above 80A, open Door A",
		"objective_pass_door": "HUMAN: pass through Door A",
		"objective_cross_laser": "AI: suppress laser / HUMAN: cross corridor",
		"objective_release_exit": "AI: release the exit lock",
		"objective_enter_airlock": "HUMAN: enter the extraction airlock",
		"objective_complete": "Mission complete — Sector A evacuated",
		"objective_failed": "Mission failed — return to title",
		"location_arrival": "Arrival bay",
		"location_door": "Door A checkpoint",
		"location_interior": "Sector A interior",
		"location_laser": "Laser corridor",
		"location_exit": "Extraction Zone",
		"location_evacuated": "Evacuated / Airlock",
		"world_field_feed": "SECTOR A // FIELD FEED",
		"world_live": "LIVE %s",
		"world_arrival": "ARRIVAL BAY",
		"world_sector": "SECTOR A",
		"world_laser": "LASER CORRIDOR",
		"world_extraction": "EXTRACTION",
		"world_door": "DOOR A",
		"world_exit": "EXIT",
		"world_field": "FIELD",
		"sender_control": "CONTROL",
		"sender_field": "FIELD",
		"sender_system": "SYSTEM",
		"sender_warning": "WARNING",
		"message_initial": "Control link established. Move to Door A and report when ready.",
		"message_shield_on": "Field shield enabled.",
		"message_shield_off": "Field shield disabled.",
		"message_laser_suppressed": "Laser suppressed for 6 seconds.",
		"message_door_need_shield": "Door A denied: enable the field shield first.",
		"message_door_need_current": "Door A denied: current must exceed 80A.",
		"message_door_open": "Door A unlocked. Passage is open.",
		"message_exit_denied": "Exit denied: human operator is not at the Extraction Zone.",
		"message_exit_open": "Exit lock released. Step into the airlock.",
		"message_damage": "%s. Human HP: %d%%",
		"message_damage_reactor": "Unshielded current surge. Human HP: %d%%",
		"message_damage_laser": "Laser contact. Human HP: %d%%",
		"message_failed": "MISSION FAILED — human operator signal lost.",
		"message_complete": "MISSION COMPLETE — Sector A evacuated in %s.",
		"damage_reactor": "Unshielded current surge",
		"damage_laser": "Laser contact",
	},
}


static func text(locale: String, key: String, values: Array = []) -> String:
	var table: Dictionary = TEXT.get(locale, TEXT[EN])
	var fallback: Dictionary = TEXT[EN]
	var result := str(table.get(key, fallback.get(key, key)))
	return result % values if not values.is_empty() else result
